title: Informaticienzero
description: >- # this means to ignore newlines until "baseurl:"
  Le blog d'un informaticien passionné de partage, d'échanges et surtout, pas si zéro que ça.
baseurl: "/"
url: ""

markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5
paginate_path: "/page:num/"

excerpt_separator: "<!--excerpt-->"